service: s3-monitor
frameworkVersion: '2'
custom:
  bucket: <bucket-name-goes-here>
provider:
  name: aws
  runtime: python3.8
  stage: <environment-name-goes-here>
  region: <aws-region-goes-here>

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::*'

package:
  include:
    - handler.py
  exclude:
    - .gitignore
    - serverless.yml

functions:
  monitor:
    handler: handler.monitor
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:Put
          existing: true
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:Post
          existing: true 
    environment:
      BUCKET: ${file(./env.${self:provider.stage}.json):BUCKET}
